# Generated by Django 3.2.4 on 2021-06-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='publishing_datetime',
            new_name='published_at',
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
